apiVersion: v1
kind: pod
metadata:
  name: nginx-service-pod
  labels:
    project: Bcom
    environment: regression
    name: Macys
    cluster: Non-trans
spec:
  containers:
  - name: nginx
    image: nginx