apiVersion: v1 
kind: Service
metadata:
  name:  Service-nodeport
spec:
  type: NodePort
  selector:
    project: Bcom
    environment: regression
    name: Macys
    cluster: Non-trans
  ports:
  - name:  name-of-the-port
    port:  80   #service port
    targetPort:  8080 #traget port